{% set name = "homonim" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/homonim-{{ version }}.tar.gz
  sha256: 9fa22df461f942dc92e56ecb30630431655cf563359682e84122e3b70e118ab8

build:
  entry_points:
    - homonim=homonim.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click >=8
    - numpy >=1.19
    - opencv >=4.5
    - python >=3.6
    - pyyaml >=5.4
    - rasterio >=1.1
    - tqdm >=4.6
    - cloup >=0.15
    - tabulate >=0.8

test:
  imports:
    - homonim
  commands:
    - homonim --help
  requires:
    - pip

about:
  home: https://github.com/leftfield-geospatial/homonim
  summary: |
    Correct aerial and satellite imagery to surface reflectance.
  license: AGPL-3.0-only
  license_file: LICENSE
  description: |
    `homonim` provides a command line interface and API for correcting 
    remotely sensed imagery to approximate surface reflectance.  It is a form 
    of *spectral harmonisation*, that adjusts for spatially varying 
    atmospheric and anisotropic (BRDF) effects, by fusion with satellite 
    surface reflectance data.  Manual reflectance measurements and target
    placements are not required.
    
    It is useful as a pre-processing step for quantitative mapping 
    applications such as biomass estimation or precision agriculture, and for 
    reducing seamlines and other visual artefacts in image mosaics.  It can be 
    applied to multi-spectral drone, aerial and satellite imagery.

  dev_url: https://github.com/leftfield-geospatial/homonim
  doc_url: https://homonim.readthedocs.io

extra:
  recipe-maintainers:
    - dugalh
