[project]
name = 'homonim'
description = 'Correct drone, aerial and satellite imagery to surface reflectance.'
readme = 'README.rst'
requires-python = '>=3.10'
dependencies = [
    'rasterio>=1.1',
    'opencv-python>=4.5',
    'numpy>=1.19',
    'click>=8',
    'tqdm>=4.6',
    'pyyaml>=5.4',
    'tabulate>=0.8',
]
authors = [{ name = 'Leftfield Geospatial' }]
license = 'AGPL-3.0-or-later'
license-files = ['LICENCSE']
keywords = [
    'drone', 'aerial', 'satellite', 'image', 'surface reflectance', 'correction',
    'harmonization', 'brdf', 'atmospheric'
]
classifiers = [
    'Programming Language :: Python :: 3',
    'Operating System :: OS Independent',
]
dynamic = ['version']

[project.scripts]
homonim = 'homonim.cli:cli'

[dependency-groups]
tests = ['pytest', 'pytest-xdist', 'pytest-cov']
docs = ['sphinx', 'furo', 'sphinx-click', 'sphinx-copybutton', 'nbsphinx']

[project.urls]
Homepage = 'https://github.com/leftfield-geospatial/homonim'
Source = 'https://github.com/leftfield-geospatial/homonim'
Documentation = 'https://homonim.readthedocs.io'
Changelog = 'https://github.com/leftfield-geospatial/homonim/releases'
Issues = 'https://github.com/leftfield-geospatial/homonim/issues'

[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[tool.setuptools]
packages = ['homonim']

[tool.setuptools.dynamic]
version = { attr = 'homonim.version.__version__' }

[tool.setuptools.package-data]
homonim = ['py.typed']

[tool.ruff]
line-length = 88
format = { quote-style = 'single' }

[tool.ruff.lint]
select = [
    'B', # flake8-bugbear
    'E', # pycodestyle error
    'F', # pyflakes
    'I', # isort
    'UP', # pyupgrade
    'W', # pycodestyle warning
    'RUF'
]
