# Test publishing to, and installing and running with Test PyPI

name: Install & test PyPI package
on:
  workflow_dispatch:

jobs:
  # Install homonim from Test PyPI and test CLI
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
      - uses: actions/checkout@v2   # checkout repository with test data
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install homonim from Test PyPI
        run: |
          python -m pip install --upgrade pip
          python -m pip install homonim
      - name: Test homonim CLI
        timeout-minutes: 5
        run: |
          pwd
          ls -R
          mkdir ./tests/data/corrected/
          homonim fuse --help
          homonim fuse -m gain-blk-offset -k 5 5 -od ./tests/data/corrected -o ./tests/data/source/aerial_rgb_byte_1.tif  ./tests/data/reference/LANDSAT-LC08-C02-T1_L2-LC08_171083_20150923_B432_Byte.tif
          ls ./tests/data/corrected/*
          test -f ./tests/data/corrected/aerial_rgb_byte_1_RGB_FUSE_cREF_mGAIN-BLK-OFFSET_k5_5.tif && echo "Test OK"
