# Test publishing to, and installing and running with Test PyPI

name: Install & test TestPyPI package
on:
  workflow_dispatch:

jobs:
  # Install homonim from Test PyPI and test CLI
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        python-version: [ 3.6, 3.7, 3.8, 3.9, 3.10 ]
    steps:
      - uses: actions/checkout@v2   # checkout repository with test data
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install homonim from Test PyPI
        run: |
          python -m pip install --upgrade pip
          python -m pip install --extra-index-url https://test.pypi.org/simple/ --upgrade homonim
      - name: Test homonim CLI
        timeout-minutes: 5
        run: |
          cd tests/data
          mkdir corrected
          homonim fuse --help
          homonim fuse -m gain-blk-offset -k 5 5 -od ./corrected -cmp -o ./source/ngi_rgb_byte_1.tif  ./reference/landsat8_byte.tif
          ls ./corrected/*
          test -f ./corrected/ngi_rgb_byte_1_FUSE_cREF_mGAIN-BLK-OFFSET_k5_5.tif && echo "Test OK"
