name: Install & test conda-forge package
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: [ '3.10', '3.14' ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v7  # for the test data

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v4
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          activate-environment: homonim-test
          conda-solver: libmamba

      - name: Install package
        run: |
          conda info
          conda install homonim>=0.4.3
          conda list

      - name: Install OpenCV Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 libopengl0

      - name: Run CLI fusion test
        timeout-minutes: 5
        run: |
          cd tests/data
          mkdir corrected
          homonim fuse --help
          homonim fuse -m gain-blk-offset -k 5 5 -od ./corrected -cmp -o ./source/ngi_rgb_byte_1.tif  ./reference/landsat8_byte.tif
          ls ./corrected/*
          test -f ./corrected/ngi_rgb_byte_1_FUSE_cREF_mGAIN-BLK-OFFSET_k5_5.tif && echo "Test OK"
