# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Integration Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-xdist
        python -m pip install rasterio opencv-python-headless numpy click tqdm pyyaml cloup tabulate

    - name: Test with pytest
      timeout-minutes: 5
      run: |
        python -m pytest -n auto ./tests/integration.py
